name: AppWright Test

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests fastapi uvicorn

      - name: Start backend server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Submit AppWright test job
        run: |
          python qgjob.py submit --org-id qualgent --app-version-id xyz123 --test tests/onboarding.spec.js

      - name: Poll job status (example)
        run: |
          # You can implement a simple loop here to poll status and fail if job fails
          echo "Polling for job status would go here."
