name: AppWright Test

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Backend Server (Background)
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 &

      - name: Wait for Backend to Start
        run: sleep 5

      - name: Submit Test Job via CLI
        run: |
          python qgjob.py submit \
            --org-id=qualgent \
            --app-version-id=xyz123 \
            --test=tests/onboarding.spec.js

      - name: Check Status
        run: |
          python qgjob.py status --job-id=abc456 || echo "Status check failed (dummy example)"
